[package]
name = "image-server-preview"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
clip2preview.workspace = true
image.workspace = true
image-server-store = { path = "../image-server-store" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
