[package]
name = "canvas-mirror-preview"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
clip2preview.workspace = true
crc32fast = "1"
flate2 = "1"
image.workspace = true
lcms2.workspace = true
canvas-mirror-store = { path = "../canvas-mirror-store" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
