[package]
name = "image-server-watcher"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
image-server-core = { path = "../image-server-core" }
image-server-model = { path = "../image-server-model" }
image-server-store = { path = "../image-server-store" }
notify.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
image-server-config = { path = "../image-server-config" }
tempfile.workspace = true

[lints]
workspace = true
